# Security templates kept and aligned to stages above
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

.pnpm:
  image: node:lts-alpine
  variables:
    PNPM_STORE_DIR: .pnpm-store
  cache:
    key:
      files:
      - pnpm-lock.yaml
    paths:
    - .pnpm-store/
    policy: pull-push
  before_script:
  - corepack enable pnpm
  - pnpm --version
  - pnpm config set store-dir "$PNPM_STORE_DIR"
  - pnpm install --frozen-lockfile

build:
  extends: .pnpm
  stage: build
  script:
  - pnpm check
  - pnpm build

test:
  extends: .pnpm
  stage: test
  script:
  - pnpm test run --coverage
  artifacts:
    paths:
    - dist/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit: junit.xml
  coverage: /All files\s*\|\s*([\d\.]*)/
